language: ruby
dist: trusty
group: edge
rvm:
- 2.4.0

deploy:
  provider: heroku
  app:
    master: cob-budget
    develop: cob-budget-staging
  api_key:
    secure: "TBF3Rw9ED1KMwr6vFsxYW+G362bJmXxBwZuUW2lYu7Ni33vbLXNs4baMXJrSlZiW9V0AyPrlUHxqUn/EEVmDUiTTPUSix2bhkVHCigcQZ36Y/Hswq9oQb86MFGJyunHtBl8Yo3Skxbzum6ZAkJ+iy1VOorsSgldguqQeEs1xMXEKc9S38Ig1/UX4RmNmHDEkfpt5Lxvwcrdj9KZRLMSmcxnCmyri6NLtlacjEQq6XstJA1+ct76F0aIrVMl6QAgTG32N7uAYDdGk7SSPtJbm5Bez0Dg0iLrIydN6NbY5Zur3surLDlqnfAkKeQtDGkyobrwV/vfv9Ne5hHplDU3b3DfrnrJIoodPrVcy7Eoc1NlCzbXqfNG23YPKrXdp0SNoxldN1BeNvCqKG+tf1kZjqcpSv0uEHKR/c+02ZPTR+14cy+bqb3WPef1PVRraCVuXFvzQw+V7vyoD+sDKmjlgSONTQIOv/3VQHp37wMBFP9+3HLohDMlJHza10gwHp32axIyeQ2Rwfu5T6S2n8WagF426z6umK2iSJRt3Uj8+m4/nGNtF4y4nxWen6qQRAeAEdN/eq68bdqUhuVtDG/3YOm+KApO2NpBSHl+3f21Gn5Tkyuw6SQ6WsmmJ2CMH9j43BwHtHymjCknVPLYBSv2Atwk7BdQdGxlo2C1bXEPivjs="

notifications:
  slack:
    secure: b2UX5FnE2/C5MDNK47EP0GZIRmfwX+18HES0Q/uSwt6t7+ogKCtIjWCp1sIPd7jqRak0VmLoM0OHy6MBjz6x+1MQMNUqPEiO1f2APgBJ48c6rzeWQKTVfrKsUvPYIA+gxQ7jq7Gn0zPYQ5/+KXkxac+NrVoH85sI0xIL2BhFgQu1W4OlLLFKT11U7zJtCi3bcYhF7/eyCcrs3+IBGGp9sldjWvaVLDqUnFjz3c5AXwxlbJ6UTq7GIdIEe5Xw/UOJS9weedhoYH2XSNzFpmqqkAGcvkFpgCeYxf12iiqkmoAq5A0CxWVXqA3vG+imabuQonpbQsGdvtFP71EV9o9DxwATwxaGhBpX+Sw4zN7v25IC6n7rcvcK2F9dtY0CAb8BpWbEbWMDXXmVvFEVAvgARQ/b+L7YOJbNbbJwJQqZkllJp0lAFluyMDwpP2Ncr177S5hR/4Z6rlj1aLK1nhbmi/tK/kSNe+bcashm7/S2KG076hN0b5TB87hsbkvHsnVJDMKXSHwKrrdJiXDAkwZbl2sBp/bbfMTXyEqrINUG4WA70WXP3lR/QJy2pldVEYIU5rRwSzZ0BJ9raF7iiXFgTn3+Yhl0U/UgcDCEKoRvutM/suCy1mQBYP+Gv1uyFNFco37doQbPeyAXNb1vjfJQtyzy8I31gIN/sK590YxLBCA=
