# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fiscal Year 2018 Recommended Budget
email: digital@boston.gov
description: > # this means to ignore newlines until "baseurl:"
  Beginning July 1, 2017 and ending June 30, 2018
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000"
twitter_username: CityOfBoston
github_username:  CityOfBoston

# Collection settings
collections:
  cabinets:
    output: true
    permalink: "/operating-budget/:collection/:path/"
  departments:
    output: true
    permalink: "/operating-budget/cabinets/:path/"
  programs:
    output: true
    permalink: "/operating-budget/cabinets/:path/"
  categories:
    output: true
    permalink: "/capital-projects/:path/"
  cp_depts:
    output: true
    permalink: "/capital-projects/:path/"
  projects:
    output: true
    permalink: "/capital-projects/:path/"

# Build settings
markdown: kramdown

exclude: [node_modules, package.json, Gulpfile, Gemfile, Gemfile.lock, vendor]
keep_files: [assets]
permalink: '/:collection/:title/'

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: "" # empty string for all files
      type: "cabinets"
    values:
      layout: "cabinets"
  - scope:
      path: "" # empty string for all files
      type: "departments"
    values:
      layout: "departments"
  - scope:
      path: "" # empty string for all files
      type: "programs"
    values:
      layout: "programs"
  - scope:
      path: "" # empty string for all files
      type: "categories"
    values:
      layout: "categories"
  - scope:
      path: "" # empty string for all files
      type: "cp_depts"
    values:
      layout: "cp_depts"
  - scope:
      path: "" # empty string for all files
      type: "projects"
    values:
      layout: "projects"

test:
  post:
    - rake test

gems:
    - jekyll-money

include: ['_pages']
