backend:
  name: github
  branch: netlifycms
  repo: jimafisk/budget.boston.gov
  base_url: https://blooming-retreat-39213.herokuapp.com
media_folder: "_source/fy18_recommended/img"
collections:
  - name: "landing-pages"
    label: "Landing Pages"
    folder: "_source/fy18_recommended/md"
    create: true 
    slug: "{{ title }}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "chapters"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      #- {label: "Components", name: "components", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "featured-analysis"
    label: "Featured Analysis"
    folder: "_source/fy18_recommended/md/featured_analysis"
    create: true 
    slug: "featured-analysis/{{ title }}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "chapters"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
